### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ask2018** [vladimiry/email-securely-app#108]
Are there any ways how to optimize the memory usage for the application or this is the prize for the way how it's working? Currently email-securely-app is the "always running application" with the most memory usage on my computer and its really far behind all the others. I have 3 protonmail accounts added and average total memory usage for all email-securely-app processes is between 700-800 MB. That's really lot for email application and it's for me atm only thing I don't like about it.

**Comment by vladimiry** [comment]
In general the memory consumption is an inevitable evil that comes with @electron platform. I think if you will open those 3 accounts in your browser at the same time, the browser also will be a resource consuming thing.

Disabling some features will allow saving some memory:
- You can disable `local store` feature for the accounts. The app then will stop keeping the emails in memory and so the memory use by the main process will be reduced. The app by design flushes and loads to memory the `database.bin` file as a whole thing but not like encrypting only the specific columns of the database in an incremental way. It's of course not an optimal approach in terms of performance and resource/memory consumption but it allows keeping the metadata hidden. You can see some implementation details [here](https://github.com/vladimiry/email-securely-app/issues/32#issuecomment-405737051). So the app by design keeps the full `local store` related database in memory.
- You can disable `full-text search` feature so the respective process won't be created. This will save 80 MB at minimum and the maximum depends on how many emails you got in your accounts (search index storing matter).

**Comment by ask2018** [comment]
Thank you for detailed answer. Local store I have already disabled. I've tried to disable the full-text search but not much difference. Yes in browser it's +- the same.  So I guess this is the price for this way of solution. You can close the issue, if there is nothing about it you can do on this platform used. Thank you.

**Comment by vladimiry** [comment]
@ask2018 I enabled optional GPU acceleration process disabling with [this commit](https://github.com/vladimiry/email-securely-app/commit/f19aa36e34c8513ce9360cc2be45ad545d556f99). This which will allow you to save some memory.

Unfortunately GPU acceleration disabling is currently blocked by upstream/electron bug but I will let you know when they fixes it.

**Comment by ask2018** [comment]
Ok great. Thank you.

**Comment by vladimiry** [comment]
@ask2018 see [2.3.3](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.3) release.

**Comment by ask2018** [comment]
Thank you. Testing version 2.3.3, but I don't see much memory usage difference. I've tried few times enable/disable the GPU acceleration with application restart and it was +- the same. Still usually between 700-800 MB, sometimes up to 900 MB for 3 protonmail accounts. If there are some differences, they are hardly noticeable in current memory usage ranges for the application.

**Comment by vladimiry** [comment]
The GPU acceleration process normally consumes just about 50-100MB of RAM, so there won't be a huge difference but if the memory use is a concern then even such improvement matters.

**Comment by ask2018** [comment]
Yes every memory save counts. That's true. But here I'm simply still in the same range of memory usage.
It varies more than 50-100 MB independently on that GPU acceleration settings for me. If I try blind test for that setting. I cannot say when it's on/off when I look just on memory usage, because sometimes there is more usage even with GPU acceleration turned off. For example if I maximize the window and then minimize back to tray. It's sometimes 100MB up and it stay there even if minimized back. As an example now there is 846 MB usage total with GPU disabled. Before there was 780 MB with GPU enabled. Before there was 750 MB if GPU disabled ect ect and  If I restart it again. It's again little bit different.

**Comment by vladimiry** [comment]
Enabling that option is up to you but it allows saving some RAM regardless of whether you see the difference since the GPU acceleration process won't be created if the option is enabled.

You are writing about other types of processes, the rendered ones which can't be dropped without hurting the functionality as they basically do the same job your browser does. This is also why your browser will consume a similar amount of RAM if you run several accounts with it.
