### ISSUE TITLE
Add option to connect more securely

### ISSUE THREAD

**Issue by nil0x42** [vladimiry/email-securely-app#29]
Protonmail has a Tor Hidden Service since early 2017 (https://protonirockerxow.onion/, as described here: https://protonmail.com/tor).

It would be nice if protonmail-desktop-app had an option to connect through onion address instead of mail.protonmail.com for extra privacy for TOR users (no need for stream isolation, no exit node)

Also, as .com TLD is owned by USA, i'd recommend to use "app.protonmail.ch" instead of "mail.protonmail.com" as default domain. this is the original hostname for protonmail service, and it is owned by switzerland as are they server, so we keep theorical attack surface smaller (read this: https://protonmail.com/support/knowledge-base/what-is-the-difference-between-protonmail-com-and-protonmail-ch/).

I am used to submit pull requests, but i took a look in the code and have been scared as i never wrote a single line of typescript :/

Anyway, your tool is one of the rare tools that allows automatic connection to protonmail, and it is super nice. Thank you for the awesome work.

**Comment by vladimiry** [comment]
These are good points and I'm of course opened to mitigating security concerns.

Right now I'm considering to fork this project into a new app in order to add multiple encrypted mail services support, like protonmail + tutanota at least (are there more alike services?). Should not be a hard thing to do, but would involve some refactoring happening. Having decided to do such fork I'd prefer to finish that task first, and then handle this issue. Otherwise, this issue is going to be a next thing to handle.

**Comment by vladimiry** [comment]
Going to publish new project with Tutanota and domain entry point selection support soon, I think withing a week.

**Comment by nil0x42** [comment]
i will be happy to try it !

**Comment by vladimiry** [comment]
Domain selection is now supported with recent release https://github.com/vladimiry/email-securely-app/releases/tag/v1.0.0

All the available domains are now centralized in [single place](https://github.com/vladimiry/email-securely-app/blob/176f0118f8e31a187ed18c3657474b9e91697464/src/shared/constants.ts#L23).

Closing as resolved, feel free to reach out if something is still missing.

![domain selection](https://user-images.githubusercontent.com/1560781/42399747-b72539a2-8177-11e8-91ae-5ac95630e6b6.png)
