### ISSUE TITLE
Toggling app through launcher is very slow.

### ISSUE THREAD

**Issue by freed00m** [vladimiry/email-securely-app#44]
If app is running and minized in the tray arrea, running the cli command `~$ email-securely-app` will correctly shows the windows however this takes a long time :(
But if I click on the tray arrea the windows is drawn instantly.

I want to toggle  email-securely-app from keyboard shortcut and my script is looking like this

```
#!/bin/bash
FOUNDONE=0

wmctrl -l | grep "Unofficial desktop app for E2E encrypted email providers"
if [ $? -eq 0 ]; then ((FOUNDONE++)) 
fi

echo $FOUNDONE

if [ $FOUNDONE -eq 0 ]; then
    email-securely-app
else 
    wmctrl -c "Unofficial desktop app for E2E encrypted email providers"
fi
```

But I have to wait half a second until the windows is raised.

Is there some signal I could send to the running app that would have the same effect as the "toogle window" option in the tray menu?

**Comment by vladimiry** [comment]
There is the same `activateBrowserWindow` function used in both cases to show the main window, [toggling by tray icon](https://github.com/vladimiry/email-securely-app/blob/d24ce8cd9352d770b0ace55f4ff1ee15e0df1228/src/electron-main/util.ts#L100) and second instance running [callback](https://github.com/vladimiry/email-securely-app/blob/d24ce8cd9352d770b0ace55f4ff1ee15e0df1228/src/electron-main/index.ts#L25). So there is not a lot I can do about speeding up window showing by running a second app second instance, since second instance callback running is being triggered by the Electron's `app.makeSingleInstance` function which I don't control.

Nevertheless, I've added a small optimization to [this](https://www.dropbox.com/s/xxay30m7ruu9ymj/email-securely-app-1.4.1-linux.pacman?dl=1) version (earlier "makeSingleInstance" callback execution). But I would only expect a significant improvement with newer Electron versions speeding up `app.makeSingleInstance` function executing.

So closing for now, but I'm opened for possible ideas and workarounds.
