### ISSUE TITLE
Command + H does not hide app on mac

### ISSUE THREAD

**Issue by dontbuymonero** [vladimiry/email-securely-app#50]
The only way to hide/unhide app right now is to click on the icon in the menu bar and select toggle window.

**Comment by vladimiry** [comment]
Not exactly the only way :sunglasses: Another way of main app window showing is to execute the app's binary, including binding this action to any hotkey you want, see [here](https://github.com/vladimiry/email-securely-app/issues/44) how @freed00m does it :smiley: It works since the app prevents multiple versions running and when the second instance starts the app cancels it with openging the main window of the original instance in callback.

Going to look into enabling Command + H case.

**Comment by freed00m** [comment]
Just wanted to say the utility for window control os not working under wayland. :(

**Comment by vladimiry** [comment]
@dontbuymonero can you try [this](https://www.dropbox.com/s/796u2mw2pmclmd5/email-securely-app-1.5.3-mac.dmg?dl=1) version (or [beta](https://www.dropbox.com/s/l5phfj04nv9kb2q/email-securely-app-2.0.0-beta.4-mac.dmg?dl=1) if your prefer)? It enables the following macOS related features:
- basic app window menu
- cmd+h command
- showing app window on dock icon click

**Comment by vladimiry** [comment]
Fix is going to be published soon with a new release.

**Comment by vladimiry** [comment]
Changes got released with [1.5.3](https://github.com/vladimiry/email-securely-app/releases/tag/v1.5.3).
