### ISSUE TITLE
Sudden spike in CPU usage 

### ISSUE THREAD

**Issue by Ghost-Recon131** [vladimiry/email-securely-app#59]
For some reason, I will get a sudden spike in CPU usage. Not exactly sure when it started happening, but it might have been today after updating Firefox to 63.0. 
<img width="733" alt="capture" src="https://user-images.githubusercontent.com/40227626/47432193-4f255a80-d7e9-11e8-906e-3864c8117d5d.PNG">

**Comment by vladimiry** [comment]
Thanks for the info. Unfortunately, there is not a lot I can do in order to investigate the issue not knowing how to reproduce it. If that's not a recurring problem I'd suggest closing the issue unless you are going to provide more info (like at least log file in debug mode, the exact time when it happened and sub-processes information). Although even having more info there is no guarantee that issue cause will be revealed since the app at the moment doesn't have an advanced built-in diagnostic means and besides it might be related to the Protonmail/Tutanota code that I don't control.

**Comment by Ghost-Recon131** [comment]
Thanks for the reply, I’ll see if I can get more information on what’s causing it.
