### ISSUE TITLE
Mac CMD+C and CMD+V do not allow Copy/Paste in emails

### ISSUE THREAD

**Issue by ohkeepa** [vladimiry/email-securely-app#67]
Running 2.0.0-beta.5 on Mac with all updates

**Comment by vladimiry** [comment]
Do the respective context menu actions work?

**Comment by vladimiry** [comment]
@ohkeepa can you try a build from [this](https://www.dropbox.com/sh/rrg0pj8x4jb6hwr/AABrk2yVgs7_EjJ1Dyd5lzACa?dl=0&lst=) folder? Copy/pasting using hotkeys works if I run macOS under a virtual machine, but it might be not the same as running on a real device. Also asking @joshirio to try it.

**Comment by joshirio** [comment]
Copying with CMD+C works when viewing an email but not when composing (writing) one.

It works if you use the context menu though. Maybe if the context menu actions in the composing window get CMD+C/V assigned it might work.

**Comment by vladimiry** [comment]
>  Maybe if the context menu actions in the composing window get CMD+C/V assigned it might work.

According to the documentation to make hotkeys work on macOS I will need to add respective actions to the main app menu, not to the context menu, so it would be a sort of app global hotkeys. I didn't want to extend the main app menu and tried to go with a workaround which as we can see doesn't work fully properly.

So going to extend the main app menu for macOS only. It still might not be working due to opened Electron bugs (like [this](https://github.com/electron/electron/issues/15219) and [this](https://github.com/electron/electron/issues/15728)), but we better try it in our own.

**Comment by joshirio** [comment]
Yeah, never programmed with electron only with Qt so that was just a guess. I think as long as the context menus work it's usable, thanks

**Comment by vladimiry** [comment]
It's usable, but I'd like to close known bugs before releasing the final v2 version.

**Comment by vladimiry** [comment]
@joshirio can you try updated build in the same [Dropbox folder](https://www.dropbox.com/sh/rrg0pj8x4jb6hwr/AABrk2yVgs7_EjJ1Dyd5lzACa?dl=0&lst=). There are two different implementations, `role` and `custom` subfolders, hope at least one of them is working well.

**Comment by vladimiry** [comment]
So the issue remains open, have not more ideas for now.

**Comment by vladimiry** [comment]
> Copying with CMD+C works when viewing an email but not when composing (writing) one.

I looked deeper into the copy/pasting not working while composing issue and seem to found out why it didn't work. It's because message editing is happening inside a dynamically created iframe element. So now I'm processing the dynamically created iframes too and so hopefully all the cases will be properly handled with a new version uploaded [here](https://www.dropbox.com/sh/rrg0pj8x4jb6hwr/AABrk2yVgs7_EjJ1Dyd5lzACa?dl=0&lst=). Can someone try it? I promise there will be no more new builds for today :blush:

**Comment by ohkeepa** [comment]
That works!  Thank you!
