### ISSUE TITLE
New provider: MsgSafe.io

### ISSUE THREAD

**Issue by vensko** [vladimiry/email-securely-app#71]
I'd like to suggest to add support for [MsgSafe.io](https://www.msgsafe.io/) - privacy-focused email service, based in Panama, that is very similar to already supported providers. It ticks a lot of boxes and, I think, would be a great addition.

**Comment by vladimiry** [comment]
Thanks for the feature request, I was not aware of MsgSafe before. Unfortunately, none of MsgSafe is currently open-sourced while Protonmail and Tutanota have open-sourced the client-side code at least. Besides, ideally the code is open-sourced with types (like TypeScript, Flow, etc) + API documentation + API to be public (so if they introduce breaking change, they do announcement and increase the API version). It would be much harder to support a [local store](https://github.com/vladimiry/email-securely-app/issues/32) feature having no code opened since it requires a deep integration with the mail provider's client-side code.
So I'm closing the issue with won't fix status due to a lack of the capacity to support an email provider that has not open-sourced its client-side code at least.
