### ISSUE TITLE
Spam and unread notification (count)

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#86]
Since version 2.0.0 the app shows notifications and unread count indicator on spam folder but only if the local storage feature is enabled. I think it would make sense to preserve the feature as it was previously, meaning no notifications and unread status indicator for spam emails.

Is this intentional or a by product of the local email view that just checks for all folders?
I have an account which is getting spam mails all the time and would like, if possible, to be notified only for real emails.

**Comment by vladimiry** [comment]
This is the result of [this](https://github.com/vladimiry/email-securely-app/issues/30#issuecomment-419098555) feature enabing in along with enabling local store option.

So in the case of local store enabling unread counters will be derived from the entire local store instead of listening for Protonmail itself calls [/api/messages/count](https://github.com/vladimiry/email-securely-app/blob/master/src/electron-preload/webview/protonmail/api.ts#L304) API and picking the unread values from there.

Certainly spam folders can be omitted during local store scanning.

**Comment by vladimiry** [comment]
The pre v2.1.0 version is uploaded [here](https://www.dropbox.com/sh/7sbderca1bqhjgd/AAAm8tMMUdy8PW_6W49Bizrna?dl=0&lst=). Does it work as expected?

In database mode spam emails are still shown as unread since I really prefer database mode shows a complete picture.

**Comment by joshirio** [comment]
yes, perfect!
thanks.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Freitag, 28. Dezember 2018 22:50 schrieb Vladimir Yakovlev <notifications@github.com>:

**Comment by vladimiry** [comment]
Closing as resolved. The feature will be a part of the next release.

**Comment by vladimiry** [comment]
I've got a request describing that in some cases getting notifications for spam folders can be useful. Will consider making disabling spam folders scanning configurable.

**Comment by vladimiry** [comment]
Resolved with [v2.2.0](https://github.com/vladimiry/email-securely-app/releases/tag/v2.2.0) release.
