### ISSUE TITLE
how vanilla is electron's chromium?

### ISSUE THREAD

**Issue by MalevolentGrin** [vladimiry/email-securely-app#89]
If the focus is privacy could a less googley build be used?

https://github.com/Eloston/ungoogled-chromium

**Comment by vladimiry** [comment]
The app is built on Electron, so such kind of requests should go there. There was already related issue placed https://github.com/electron/electron/issues/14784 but got rejected until detailed information about which exact features need to be disabled in order to strengthen the privacy provided. So if you have got a specific idea, I believe you might want to share it there.
